
<!--
**BorisRomaoAntunes/BorisRomaoAntunes** is a ✨ _special_ ✨ repository because its `README.md` (this file) appears on your GitHub profile.

Here are some ideas to get you started:

- 🔭 I’m currently working on ...
- 🌱 I’m currently learning ...
- 👯 I’m looking to collaborate on ...
- 🤔 I’m looking for help with ...
- 💬 Ask me about ...
- 📫 How to reach me: ...
- 😄 Pronouns: ...
- ⚡ Fun fact: ...
-->

## 👨🏿‍💻  E aí! Eu sou o Boris. Por enquanto estou aprendendo e melhorando minhas habilidades de desenvolvedor. Estou aqui para mudar minha vida! O futuro é top!🚀
   👨🏿‍💻 Whats up!I'm Boris. For now I'm learning and improving my developer skills.
<div style="display: inline_block"><br>
  <img align="center" alt="Rafa-Js" height="90" width="100" src="https://cdn.jsdelivr.net/gh/devicons/devicon/icons/swift/swift-original.svg">
</div>
