# Olá! eu sou o Kauê Dias👋🏻
[![Typing SVG](https://readme-typing-svg.herokuapp.com/?color=fff&size=35&center=true&vCenter=true&width=1000&lines=Bem+vindo+ao+meu+perfil+do+GitHub!+:%29)](https://git.io/typing-svg)

### Meu nome é Kauê sou de Sâo Paulo - SP, sou estudante desenvolvimento back-end, estou ingressando na área de tecnologia agora.
### Atualmente cursando Análise e Desenvolvimento de Sistemas na DIO.
